# Generated by Django 3.1 on 2022-05-08 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store_product', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('weight', 'weight')], max_length=100),
        ),
    ]
